# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            GSoC'18 @ CERN
tagline:          'Professional Blog'
description:      'Google Summer of Code 2018 Progress @ CERN-HSF by Ravi Kiran S.'
url:              http://www.sravikiran.com/GSOC18/
baseurl:          /GSOC18/

author:
  name:           'Ravi Kiran S'
  url:            http://www.sravikiran.com

gems:             [jekyll-paginate,jekyll-gist]
paginate:         3
paginate_path:    "page:num"
